<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (COD_CAT_PRODUCTO?,COD_PRODUCTO?,COD_MONEDA?,DESCRIPCION?,COD_EMPRESA?,DETALLE?,CLTE_PROSPECTO?,NOM_FILTRO?,NOM_IMAGEN?,ABREVIATURA?,REQUERIMIENTOS?,COD_PRODUCTO_SB?,TIPO_PERSONA?,TIPO_INSTRUMENTO_SB?)+>
  <!ELEMENT COD_CAT_PRODUCTO (#PCDATA)>
  <!ELEMENT COD_PRODUCTO (#PCDATA)>
  <!ELEMENT COD_MONEDA (#PCDATA)>
  <!ELEMENT DESCRIPCION (#PCDATA)>
  <!ELEMENT COD_EMPRESA (#PCDATA)>
  <!ELEMENT DETALLE (#PCDATA)>
  <!ELEMENT CLTE_PROSPECTO (#PCDATA)>
  <!ELEMENT NOM_FILTRO (#PCDATA)>
  <!ELEMENT NOM_IMAGEN (#PCDATA)>
  <!ELEMENT ABREVIATURA (#PCDATA)>
  <!ELEMENT REQUERIMIENTOS (#PCDATA)>
  <!ELEMENT COD_PRODUCTO_SB (#PCDATA)>
  <!ELEMENT TIPO_PERSONA (#PCDATA)>
  <!ELEMENT TIPO_INSTRUMENTO_SB (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>206</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>Cuenta de Ahorro Infantil Pesos &#40;P.Fisica&#41;</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CC02</ABREVIATURA>
    <COD_PRODUCTO_SB>213</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>213</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>207</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>Cuenta de Nomina Empleados Ademi Pesos &#40;P.Fisica&#41;</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CC02</ABREVIATURA>
    <COD_PRODUCTO_SB>213</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>213</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>221</COD_PRODUCTO>
    <COD_MONEDA>2</COD_MONEDA>
    <DESCRIPCION>Cuenta de Ahorro en Dolares &#40;P.Juridica&#41;</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CC02</ABREVIATURA>
    <COD_PRODUCTO_SB>213</COD_PRODUCTO_SB>
    <TIPO_PERSONA>J</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>213</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>PR</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>503</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>Cr&#233;ditos consumo en pesos</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>PR01</ABREVIATURA>
    <COD_PRODUCTO_SB>161</COD_PRODUCTO_SB>
    <TIPO_PERSONA>A</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>161</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>PR</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>504</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>Cr&#233;ditos Hipotecarios en pesos</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>PR01</ABREVIATURA>
    <COD_PRODUCTO_SB>181</COD_PRODUCTO_SB>
    <TIPO_PERSONA>A</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>181</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CD</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>322</COD_PRODUCTO>
    <COD_MONEDA>2</COD_MONEDA>
    <DESCRIPCION>Certificados financieros Capitalizable D&#243;lares  &#40;P.Fisica&#41;</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CD01</ABREVIATURA>
    <COD_PRODUCTO_SB>221</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>221</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CD</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>323</COD_PRODUCTO>
    <COD_MONEDA>2</COD_MONEDA>
    <DESCRIPCION>Certificados financieros Capitalizable D&#243;lares  &#40;P.Juridica&#41;</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CD01</ABREVIATURA>
    <COD_PRODUCTO_SB>221</COD_PRODUCTO_SB>
    <TIPO_PERSONA>J</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>221</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4101</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA CLASICA INT. STAFF</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>171</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>171</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4151</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA CLASICA INTERNACIONAL</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>171</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>171</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4181</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA CLASICA INT. OFERTA NEG. 1</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>171</COD_PRODUCTO_SB>
    <TIPO_PERSONA>A</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>171</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4201</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA CLASICA LOCAL STAFF</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>171</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>171</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4251</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA CLASICA LOCAL</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>171</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>171</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4281</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA CLASICA LOCAL OFERTA NEG. 1</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>171</COD_PRODUCTO_SB>
    <TIPO_PERSONA>A</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>171</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4301</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA CLASICA LOCAL HIPEROLE EMPLEADO</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>171</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>171</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4351</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA CLASICA LOCAL HIPEROLE CLIENTES</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>171</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>171</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4401</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA GOLD INT. - STAFF</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>172</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>172</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4451</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA GOLD INTERNACIONAL</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>172</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>172</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4481</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA GOLD INT. OFERTA NEG. 1</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>172</COD_PRODUCTO_SB>
    <TIPO_PERSONA>A</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>172</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4501</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA FLEXIBLE EMPLEADOS</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>171</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>171</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4531</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA BLUE COUNTRY MINORISTA</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>171</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>171</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4551</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA FLEXIBLE CLIENTES</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>171</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>171</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4581</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA FLEXIBLE OFERTA</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>171</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>171</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4601</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA EMPRESARIAL FLOTILLA STAFF</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>132</COD_PRODUCTO_SB>
    <TIPO_PERSONA>J</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>132</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4611</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA EMP. LOCAL FLOTILLA STAFF</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>134</COD_PRODUCTO_SB>
    <TIPO_PERSONA>J</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>134</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4641</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA BLUE COUNTRY MAYORISTA</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>132</COD_PRODUCTO_SB>
    <TIPO_PERSONA>J</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>132</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4711</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA EMPRESARIAL&#160; INVERSIONES TITANIO FLOTILLA</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>134</COD_PRODUCTO_SB>
    <TIPO_PERSONA>J</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>134</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4751</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA EXPENDIO DE COMBUSTIBLE</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>132</COD_PRODUCTO_SB>
    <TIPO_PERSONA>J</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>132</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4761</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA EMPRESARIAL PLUS INTERNACIONAL STAFF</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>132</COD_PRODUCTO_SB>
    <TIPO_PERSONA>J</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>132</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4791</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA EMPRESARIAL PLUS INTERNACIONAL&#160;</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>132</COD_PRODUCTO_SB>
    <TIPO_PERSONA>J</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>132</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4801</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA EMPRESARIAL INTERNACIONAL STAFF</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>132</COD_PRODUCTO_SB>
    <TIPO_PERSONA>J</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>132</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4851</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA EMPRESARIAL</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>132</COD_PRODUCTO_SB>
    <TIPO_PERSONA>J</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>132</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4881</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA EMPRESARIAL INTERNACIONAL. OFERTA NEG. 1</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>132</COD_PRODUCTO_SB>
    <TIPO_PERSONA>J</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>132</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4901</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA EMPRESARIAL LOCAL STAFF</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>132</COD_PRODUCTO_SB>
    <TIPO_PERSONA>J</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>132</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4911</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA EMPRESARIAL LOCAL 007 STAFF</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>132</COD_PRODUCTO_SB>
    <TIPO_PERSONA>J</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>132</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4931</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA EMPRESARIAL MYPYME GND</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>132</COD_PRODUCTO_SB>
    <TIPO_PERSONA>J</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>132</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4951</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA EMPRESARIAL LOCAL</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>132</COD_PRODUCTO_SB>
    <TIPO_PERSONA>J</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>132</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4961</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA EMPRESARIAL LOCAL 007 CLIENTE</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>132</COD_PRODUCTO_SB>
    <TIPO_PERSONA>J</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>132</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4981</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA EMPRESARIAL LOCAL OFERTA NEG. 1</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>132</COD_PRODUCTO_SB>
    <TIPO_PERSONA>J</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>132</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>381</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>GENERICO **** CAMBIAR ****</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CD</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>320</COD_PRODUCTO>
    <COD_MONEDA>2</COD_MONEDA>
    <DESCRIPCION>Certificados financieros Pagadero D&#243;lares  &#40;P.Fisica&#41;</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CD01</ABREVIATURA>
    <COD_PRODUCTO_SB>221</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>221</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CD</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>321</COD_PRODUCTO>
    <COD_MONEDA>2</COD_MONEDA>
    <DESCRIPCION>Certificados financieros Pagadero D&#243;lares  &#40;P.Juridica&#41;</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CD01</ABREVIATURA>
    <COD_PRODUCTO_SB>221</COD_PRODUCTO_SB>
    <TIPO_PERSONA>J</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>221</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CD</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>350</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>Certificados financieros Pagadero pesos Empleados  &#40;P.Fisica&#41;</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CD01</ABREVIATURA>
    <COD_PRODUCTO_SB>221</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>221</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CD</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>351</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>Certificados financieros Capitalizable pesos Empleados  &#40;P.Fisica&#41;</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CD01</ABREVIATURA>
    <COD_PRODUCTO_SB>221</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>221</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CD</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>352</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>Certificados A Plazos pagadero pesos Empleados  &#40;P.Fisica&#41;</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CD01</ABREVIATURA>
    <COD_PRODUCTO_SB>221</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>221</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CD</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>353</COD_PRODUCTO>
    <COD_MONEDA>2</COD_MONEDA>
    <DESCRIPCION>Certificados financieros Pagadero D&#243;lares Empleados  &#40;P.Fisica&#41;</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CD01</ABREVIATURA>
    <COD_PRODUCTO_SB>221</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>221</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CD</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>354</COD_PRODUCTO>
    <COD_MONEDA>2</COD_MONEDA>
    <DESCRIPCION>Certificados financieros Capitalizable D&#243;lares Empleados  &#40;P.Fisica&#41;</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CD01</ABREVIATURA>
    <COD_PRODUCTO_SB>221</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>221</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>TC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>4071</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>VISA FLOTILLA COMBUSTIBLE CLIENTE</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>TC01</ABREVIATURA>
    <COD_PRODUCTO_SB>174</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>174</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>100</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>CC Personal Normal</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CC01</ABREVIATURA>
    <COD_PRODUCTO_SB>211</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>211</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>101</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>CC Personal Microempresa</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CC01</ABREVIATURA>
    <COD_PRODUCTO_SB>211</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>211</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>102</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>CC Comercial Tipo A</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CC01</ABREVIATURA>
    <COD_PRODUCTO_SB>211</COD_PRODUCTO_SB>
    <TIPO_PERSONA>J</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>211</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>103</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>CC Comercial Tipo B</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CC01</ABREVIATURA>
    <COD_PRODUCTO_SB>212</COD_PRODUCTO_SB>
    <TIPO_PERSONA>J</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>212</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>203</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>Cuenta de Ahorro Mi Inicial Te Reto por un Sue&#241;o</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CC02</ABREVIATURA>
    <COD_PRODUCTO_SB>213</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>213</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>200</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>Cuenta de Ahorro Normal Pesos &#40;P.Fisica&#41;</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CC02</ABREVIATURA>
    <COD_PRODUCTO_SB>213</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>213</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>201</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>Cuenta de Ahorro Normal Pesos &#40;P.Juridica&#41;</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CC02</ABREVIATURA>
    <COD_PRODUCTO_SB>213</COD_PRODUCTO_SB>
    <TIPO_PERSONA>J</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>213</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CD</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>300</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>Certificados financieros Pagadero pesos &#40;P.Fisica&#41;</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CD01</ABREVIATURA>
    <COD_PRODUCTO_SB>221</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>221</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CD</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>301</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>Certificados financieros Pagadero pesos &#40;P.Juridica&#41;</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CD01</ABREVIATURA>
    <COD_PRODUCTO_SB>221</COD_PRODUCTO_SB>
    <TIPO_PERSONA>J</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>221</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CG</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>900</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>SUBAPLICACION GENERAL DE CONTABILIDAD DOP</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CG01</ABREVIATURA>
    <TIPO_PERSONA>A</TIPO_PERSONA>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>BA</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>901</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>Subaplicaci&#191;&#191;n General de Bancos DOP</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>BA01</ABREVIATURA>
    <TIPO_PERSONA>A</TIPO_PERSONA>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CJ</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>902</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>Subaplicaci&#243;n General de Cajas DOP</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CJ01</ABREVIATURA>
    <TIPO_PERSONA>A</TIPO_PERSONA>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>DI</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>601</COD_PRODUCTO>
    <COD_MONEDA>2</COD_MONEDA>
    <DESCRIPCION>Subaplicaci&#243;n Mercado Libre de Divisas USD</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>DI01</ABREVIATURA>
    <TIPO_PERSONA>A</TIPO_PERSONA>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>IT</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>150</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>Titulos en Moneda Nacional DOP</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>IV001</ABREVIATURA>
    <TIPO_PERSONA>A</TIPO_PERSONA>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CC</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>202</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>Cuenta de Ahorro Programado Mi Inicial Pesos &#40;P.Fisica&#41;</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CC02</ABREVIATURA>
    <COD_PRODUCTO_SB>216</COD_PRODUCTO_SB>
    <TIPO_PERSONA>F</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>216</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>GT</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>700</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>Garantias de Participaci&#191;&#191;n y Cumplimiento DOP</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>GT001</ABREVIATURA>
    <TIPO_PERSONA>A</TIPO_PERSONA>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>GT</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>701</COD_PRODUCTO>
    <COD_MONEDA>2</COD_MONEDA>
    <DESCRIPCION>Garantias de Participaci&#191;&#191;n y Cumplimiento USD</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>GT002</ABREVIATURA>
    <TIPO_PERSONA>A</TIPO_PERSONA>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>DI</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>602</COD_PRODUCTO>
    <COD_MONEDA>3</COD_MONEDA>
    <DESCRIPCION>Subaplicaci&#243;n Mercado Libre de Divisas EUR</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>DI01</ABREVIATURA>
    <TIPO_PERSONA>A</TIPO_PERSONA>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CI</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>651</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>Subaplicaci&#191;&#191;n Comercio Internacional DOP</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CI01</ABREVIATURA>
    <TIPO_PERSONA>A</TIPO_PERSONA>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CI</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>652</COD_PRODUCTO>
    <COD_MONEDA>2</COD_MONEDA>
    <DESCRIPCION>Subaplicaci&#191;&#191;n Comercio Internacional USD</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CI01</ABREVIATURA>
    <TIPO_PERSONA>A</TIPO_PERSONA>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>IV</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>903</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>Subaplicaci&#191;&#191;n de Activos Fijos e Inventarios DOP</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>IV001</ABREVIATURA>
    <TIPO_PERSONA>A</TIPO_PERSONA>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>PR</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>501</COD_PRODUCTO>
    <COD_MONEDA>2</COD_MONEDA>
    <DESCRIPCION>Cr&#233;ditos comerciales en d&#243;lares</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>PR01</ABREVIATURA>
    <COD_PRODUCTO_SB>112</COD_PRODUCTO_SB>
    <TIPO_PERSONA>A</TIPO_PERSONA>
    <TIPO_INSTRUMENTO_SB>112</TIPO_INSTRUMENTO_SB>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CV</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>801</COD_PRODUCTO>
    <COD_MONEDA>2</COD_MONEDA>
    <DESCRIPCION>Subaplicaci&#191;&#191;n Custodias Generales USD</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CV02</ABREVIATURA>
    <TIPO_PERSONA>A</TIPO_PERSONA>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CV</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>802</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>Subaplicaci&#191;&#191;n Custodias Pr&#191;&#191;stamos DOP</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CV01</ABREVIATURA>
    <TIPO_PERSONA>A</TIPO_PERSONA>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CV</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>800</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>Subaplicaci&#191;&#191;n Custodias Generales DOP</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CV01</ABREVIATURA>
    <TIPO_PERSONA>A</TIPO_PERSONA>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CV</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>803</COD_PRODUCTO>
    <COD_MONEDA>2</COD_MONEDA>
    <DESCRIPCION>Subaplicaci&#191;&#191;n Custodias Pr&#191;&#191;stamos Dolares</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CV02</ABREVIATURA>
    <TIPO_PERSONA>A</TIPO_PERSONA>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_CAT_PRODUCTO>CD</COD_CAT_PRODUCTO>
    <COD_PRODUCTO>302</COD_PRODUCTO>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>Certificados financieros Capitalizable pesos  &#40;P.Fisica&#41;</DESCRIPCION>
    <COD_EMPRESA>1</COD_EMPRESA>
    <ABREVIATURA>CD01</ABREVIATURA>