<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (COD_MONEDA?,DESCRIPCION?,OPER_CONVERSION?,ABREVIATURA?,COD_PAIS?,SIGNO?,MONEDA_ISO?,SIGLA_SB?,COD_MONEDA_TCE?,COD_MONEDA_EVERTEC?)+>
  <!ELEMENT COD_MONEDA (#PCDATA)>
  <!ELEMENT DESCRIPCION (#PCDATA)>
  <!ELEMENT OPER_CONVERSION (#PCDATA)>
  <!ELEMENT ABREVIATURA (#PCDATA)>
  <!ELEMENT COD_PAIS (#PCDATA)>
  <!ELEMENT SIGNO (#PCDATA)>
  <!ELEMENT MONEDA_ISO (#PCDATA)>
  <!ELEMENT SIGLA_SB (#PCDATA)>
  <!ELEMENT COD_MONEDA_TCE (#PCDATA)>
  <!ELEMENT COD_MONEDA_EVERTEC (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <COD_MONEDA>3</COD_MONEDA>
    <DESCRIPCION>EUROS</DESCRIPCION>
    <OPER_CONVERSION>*</OPER_CONVERSION>
    <ABREVIATURA>EUR</ABREVIATURA>
    <COD_PAIS>8</COD_PAIS>
    <SIGNO>EUR</SIGNO>
    <MONEDA_ISO>978</MONEDA_ISO>
    <SIGLA_SB>EUR</SIGLA_SB>
    <COD_MONEDA_TCE>2</COD_MONEDA_TCE>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_MONEDA>1</COD_MONEDA>
    <DESCRIPCION>PESOS</DESCRIPCION>
    <OPER_CONVERSION>/</OPER_CONVERSION>
    <ABREVIATURA>RD</ABREVIATURA>
    <COD_PAIS>1</COD_PAIS>
    <SIGNO>DOP</SIGNO>
    <MONEDA_ISO>214</MONEDA_ISO>
    <SIGLA_SB>DOP</SIGLA_SB>
    <COD_MONEDA_TCE>0</COD_MONEDA_TCE>
    <COD_MONEDA_EVERTEC>370</COD_MONEDA_EVERTEC>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_MONEDA>2</COD_MONEDA>
    <DESCRIPCION>DOLARES</DESCRIPCION>
    <OPER_CONVERSION>&#61;</OPER_CONVERSION>
    <ABREVIATURA>US</ABREVIATURA>
    <COD_PAIS>2</COD_PAIS>
    <SIGNO>USD</SIGNO>
    <MONEDA_ISO>840</MONEDA_ISO>
    <SIGLA_SB>USD</SIGLA_SB>
    <COD_MONEDA_TCE>1</COD_MONEDA_TCE>
    <COD_MONEDA_EVERTEC>371</COD_MONEDA_EVERTEC>
  </DATA_RECORD>
</main>
