<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (COD_EMPRESA?,COD_PRODUCTO?,MONTO_MINIMO?,A_LA_VISTA?,FORMA_CALCULO_INTERES?,FRE_REVISION?,PLAZO_REVISION?,FRE_INTERES?,PLAZO_INTERES?,FRE_CAPITALIZA?,PLAZO_CAPITALIZA?,PAGA_RENTA?,PORCENTAJE_RENTA?,BASE_CALCULO?,BASE_PLAZO?,PLAZO_MINIMO?,ADICIONADO_POR?,FECHA_ADICION?,MODIFICADO_POR?,FECHA_MODIFICACION?,NUM_DIAS?,TIENE_DOC_FISICO?,MODIFICA_PLA_CAP?,DIA_DE_CAP_FRE_MES?,DIA_PAGO_INT?,COD_CARTERA?,DIAS_EFECTIVO?,DIAS_CHEQUE?,MON_COM_EMISION_CHK?,CODIGO_TIPO_INSTRUMENTO?,IND_CALCULA_PENALIDAD?,IND_PENALIDAD_RENOV?,IND_REDENCION_ANT?,IND_BONOS?,IND_RENOVACION_AUTO?,IND_PRD_EMP?)+>
  <!ELEMENT COD_EMPRESA (#PCDATA)>
  <!ELEMENT COD_PRODUCTO (#PCDATA)>
  <!ELEMENT MONTO_MINIMO (#PCDATA)>
  <!ELEMENT A_LA_VISTA (#PCDATA)>
  <!ELEMENT FORMA_CALCULO_INTERES (#PCDATA)>
  <!ELEMENT FRE_REVISION (#PCDATA)>
  <!ELEMENT PLAZO_REVISION (#PCDATA)>
  <!ELEMENT FRE_INTERES (#PCDATA)>
  <!ELEMENT PLAZO_INTERES (#PCDATA)>
  <!ELEMENT FRE_CAPITALIZA (#PCDATA)>
  <!ELEMENT PLAZO_CAPITALIZA (#PCDATA)>
  <!ELEMENT PAGA_RENTA (#PCDATA)>
  <!ELEMENT PORCENTAJE_RENTA (#PCDATA)>
  <!ELEMENT BASE_CALCULO (#PCDATA)>
  <!ELEMENT BASE_PLAZO (#PCDATA)>
  <!ELEMENT PLAZO_MINIMO (#PCDATA)>
  <!ELEMENT ADICIONADO_POR (#PCDATA)>
  <!ELEMENT FECHA_ADICION (#PCDATA)>
  <!ELEMENT MODIFICADO_POR (#PCDATA)>
  <!ELEMENT FECHA_MODIFICACION (#PCDATA)>
  <!ELEMENT NUM_DIAS (#PCDATA)>
  <!ELEMENT TIENE_DOC_FISICO (#PCDATA)>
  <!ELEMENT MODIFICA_PLA_CAP (#PCDATA)>
  <!ELEMENT DIA_DE_CAP_FRE_MES (#PCDATA)>
  <!ELEMENT DIA_PAGO_INT (#PCDATA)>
  <!ELEMENT COD_CARTERA (#PCDATA)>
  <!ELEMENT DIAS_EFECTIVO (#PCDATA)>
  <!ELEMENT DIAS_CHEQUE (#PCDATA)>
  <!ELEMENT MON_COM_EMISION_CHK (#PCDATA)>
  <!ELEMENT CODIGO_TIPO_INSTRUMENTO (#PCDATA)>
  <!ELEMENT IND_CALCULA_PENALIDAD (#PCDATA)>
  <!ELEMENT IND_PENALIDAD_RENOV (#PCDATA)>
  <!ELEMENT IND_REDENCION_ANT (#PCDATA)>
  <!ELEMENT IND_BONOS (#PCDATA)>
  <!ELEMENT IND_RENOVACION_AUTO (#PCDATA)>
  <!ELEMENT IND_PRD_EMP (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <COD_EMPRESA>1</COD_EMPRESA>
    <COD_PRODUCTO>300</COD_PRODUCTO>
    <MONTO_MINIMO>5000</MONTO_MINIMO>
    <A_LA_VISTA>N</A_LA_VISTA>
    <FORMA_CALCULO_INTERES>CU</FORMA_CALCULO_INTERES>
    <FRE_CAPITALIZA>D</FRE_CAPITALIZA>
    <PLAZO_CAPITALIZA>30</PLAZO_CAPITALIZA>
    <PAGA_RENTA>S</PAGA_RENTA>
    <PORCENTAJE_RENTA>8</PORCENTAJE_RENTA>
    <BASE_CALCULO>360</BASE_CALCULO>
    <BASE_PLAZO>365</BASE_PLAZO>
    <PLAZO_MINIMO>30</PLAZO_MINIMO>
    <ADICIONADO_POR>B2000</ADICIONADO_POR>
    <FECHA_ADICION>1999/11/22 00:00:00</FECHA_ADICION>
    <MODIFICADO_POR>MASANCHEZ</MODIFICADO_POR>
    <FECHA_MODIFICACION>2017/12/07 00:00:00</FECHA_MODIFICACION>
    <TIENE_DOC_FISICO>S</TIENE_DOC_FISICO>
    <MODIFICA_PLA_CAP>N</MODIFICA_PLA_CAP>
    <DIA_PAGO_INT>26</DIA_PAGO_INT>
    <COD_CARTERA>CDPERPESOS</COD_CARTERA>
    <DIAS_EFECTIVO>0</DIAS_EFECTIVO>
    <DIAS_CHEQUE>0</DIAS_CHEQUE>
    <MON_COM_EMISION_CHK>0</MON_COM_EMISION_CHK>
    <CODIGO_TIPO_INSTRUMENTO>231</CODIGO_TIPO_INSTRUMENTO>
    <IND_CALCULA_PENALIDAD>S</IND_CALCULA_PENALIDAD>
    <IND_PENALIDAD_RENOV>N</IND_PENALIDAD_RENOV>
    <IND_REDENCION_ANT>S</IND_REDENCION_ANT>
    <IND_BONOS>N</IND_BONOS>
    <IND_RENOVACION_AUTO>S</IND_RENOVACION_AUTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_EMPRESA>1</COD_EMPRESA>
    <COD_PRODUCTO>301</COD_PRODUCTO>
    <MONTO_MINIMO>5000</MONTO_MINIMO>
    <A_LA_VISTA>N</A_LA_VISTA>
    <FORMA_CALCULO_INTERES>CU</FORMA_CALCULO_INTERES>
    <FRE_CAPITALIZA>D</FRE_CAPITALIZA>
    <PAGA_RENTA>S</PAGA_RENTA>
    <PORCENTAJE_RENTA>1</PORCENTAJE_RENTA>
    <BASE_CALCULO>360</BASE_CALCULO>
    <BASE_PLAZO>365</BASE_PLAZO>
    <PLAZO_MINIMO>30</PLAZO_MINIMO>
    <ADICIONADO_POR>B2000</ADICIONADO_POR>
    <FECHA_ADICION>1999/11/22 00:00:00</FECHA_ADICION>
    <MODIFICADO_POR>B2000</MODIFICADO_POR>
    <FECHA_MODIFICACION>2016/02/10 00:00:00</FECHA_MODIFICACION>
    <TIENE_DOC_FISICO>S</TIENE_DOC_FISICO>
    <MODIFICA_PLA_CAP>N</MODIFICA_PLA_CAP>
    <DIA_PAGO_INT>26</DIA_PAGO_INT>
    <COD_CARTERA>CDCOMPESOS</COD_CARTERA>
    <DIAS_EFECTIVO>0</DIAS_EFECTIVO>
    <DIAS_CHEQUE>0</DIAS_CHEQUE>
    <CODIGO_TIPO_INSTRUMENTO>231</CODIGO_TIPO_INSTRUMENTO>
    <IND_CALCULA_PENALIDAD>S</IND_CALCULA_PENALIDAD>
    <IND_PENALIDAD_RENOV>N</IND_PENALIDAD_RENOV>
    <IND_REDENCION_ANT>S</IND_REDENCION_ANT>
    <IND_BONOS>N</IND_BONOS>
    <IND_RENOVACION_AUTO>S</IND_RENOVACION_AUTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_EMPRESA>1</COD_EMPRESA>
    <COD_PRODUCTO>302</COD_PRODUCTO>
    <MONTO_MINIMO>5000</MONTO_MINIMO>
    <A_LA_VISTA>N</A_LA_VISTA>
    <FORMA_CALCULO_INTERES>CV</FORMA_CALCULO_INTERES>
    <FRE_CAPITALIZA>D</FRE_CAPITALIZA>
    <PLAZO_CAPITALIZA>30</PLAZO_CAPITALIZA>
    <PAGA_RENTA>S</PAGA_RENTA>
    <PORCENTAJE_RENTA>10</PORCENTAJE_RENTA>
    <BASE_CALCULO>360</BASE_CALCULO>
    <BASE_PLAZO>365</BASE_PLAZO>
    <PLAZO_MINIMO>30</PLAZO_MINIMO>
    <ADICIONADO_POR>B2000</ADICIONADO_POR>
    <FECHA_ADICION>1999/11/22 00:00:00</FECHA_ADICION>
    <MODIFICADO_POR>ICUEVA</MODIFICADO_POR>
    <FECHA_MODIFICACION>2017/07/18 00:00:00</FECHA_MODIFICACION>
    <TIENE_DOC_FISICO>S</TIENE_DOC_FISICO>
    <MODIFICA_PLA_CAP>N</MODIFICA_PLA_CAP>
    <DIA_PAGO_INT>26</DIA_PAGO_INT>
    <COD_CARTERA>CDPERPESOS</COD_CARTERA>
    <DIAS_EFECTIVO>0</DIAS_EFECTIVO>
    <DIAS_CHEQUE>0</DIAS_CHEQUE>
    <MON_COM_EMISION_CHK>0</MON_COM_EMISION_CHK>
    <CODIGO_TIPO_INSTRUMENTO>231</CODIGO_TIPO_INSTRUMENTO>
    <IND_CALCULA_PENALIDAD>S</IND_CALCULA_PENALIDAD>
    <IND_PENALIDAD_RENOV>N</IND_PENALIDAD_RENOV>
    <IND_REDENCION_ANT>S</IND_REDENCION_ANT>
    <IND_BONOS>N</IND_BONOS>
    <IND_RENOVACION_AUTO>S</IND_RENOVACION_AUTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_EMPRESA>1</COD_EMPRESA>
    <COD_PRODUCTO>303</COD_PRODUCTO>
    <MONTO_MINIMO>5000</MONTO_MINIMO>
    <A_LA_VISTA>N</A_LA_VISTA>
    <FORMA_CALCULO_INTERES>CV</FORMA_CALCULO_INTERES>
    <FRE_CAPITALIZA>D</FRE_CAPITALIZA>
    <PLAZO_CAPITALIZA>30</PLAZO_CAPITALIZA>
    <PAGA_RENTA>S</PAGA_RENTA>
    <PORCENTAJE_RENTA>1</PORCENTAJE_RENTA>
    <BASE_CALCULO>360</BASE_CALCULO>
    <BASE_PLAZO>365</BASE_PLAZO>
    <PLAZO_MINIMO>30</PLAZO_MINIMO>
    <ADICIONADO_POR>B2000</ADICIONADO_POR>
    <FECHA_ADICION>1999/11/22 00:00:00</FECHA_ADICION>
    <MODIFICADO_POR>ICUEVA</MODIFICADO_POR>
    <FECHA_MODIFICACION>2017/07/18 00:00:00</FECHA_MODIFICACION>
    <TIENE_DOC_FISICO>S</TIENE_DOC_FISICO>
    <MODIFICA_PLA_CAP>N</MODIFICA_PLA_CAP>
    <DIA_PAGO_INT>26</DIA_PAGO_INT>
    <COD_CARTERA>CDCOMPESOS</COD_CARTERA>
    <DIAS_EFECTIVO>0</DIAS_EFECTIVO>
    <DIAS_CHEQUE>0</DIAS_CHEQUE>
    <CODIGO_TIPO_INSTRUMENTO>231</CODIGO_TIPO_INSTRUMENTO>
    <IND_CALCULA_PENALIDAD>S</IND_CALCULA_PENALIDAD>
    <IND_PENALIDAD_RENOV>N</IND_PENALIDAD_RENOV>
    <IND_REDENCION_ANT>S</IND_REDENCION_ANT>
    <IND_BONOS>N</IND_BONOS>
    <IND_RENOVACION_AUTO>S</IND_RENOVACION_AUTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_EMPRESA>1</COD_EMPRESA>
    <COD_PRODUCTO>304</COD_PRODUCTO>
    <MONTO_MINIMO>50001</MONTO_MINIMO>
    <A_LA_VISTA>N</A_LA_VISTA>
    <FORMA_CALCULO_INTERES>CU</FORMA_CALCULO_INTERES>
    <FRE_CAPITALIZA>D</FRE_CAPITALIZA>
    <PLAZO_CAPITALIZA>0</PLAZO_CAPITALIZA>
    <PAGA_RENTA>S</PAGA_RENTA>
    <PORCENTAJE_RENTA>10</PORCENTAJE_RENTA>
    <BASE_CALCULO>360</BASE_CALCULO>
    <BASE_PLAZO>365</BASE_PLAZO>
    <PLAZO_MINIMO>365</PLAZO_MINIMO>
    <ADICIONADO_POR>B2000</ADICIONADO_POR>
    <FECHA_ADICION>1999/11/22 00:00:00</FECHA_ADICION>
    <MODIFICADO_POR>MASANCHEZ</MODIFICADO_POR>
    <FECHA_MODIFICACION>2018/10/24 00:00:00</FECHA_MODIFICACION>
    <TIENE_DOC_FISICO>S</TIENE_DOC_FISICO>
    <MODIFICA_PLA_CAP>N</MODIFICA_PLA_CAP>
    <DIA_PAGO_INT>26</DIA_PAGO_INT>
    <COD_CARTERA>CDPLAPESOS</COD_CARTERA>
    <DIAS_EFECTIVO>0</DIAS_EFECTIVO>
    <DIAS_CHEQUE>0</DIAS_CHEQUE>
    <MON_COM_EMISION_CHK>0</MON_COM_EMISION_CHK>
    <CODIGO_TIPO_INSTRUMENTO>221</CODIGO_TIPO_INSTRUMENTO>
    <IND_CALCULA_PENALIDAD>S</IND_CALCULA_PENALIDAD>
    <IND_PENALIDAD_RENOV>N</IND_PENALIDAD_RENOV>
    <IND_REDENCION_ANT>N</IND_REDENCION_ANT>
    <IND_BONOS>N</IND_BONOS>
    <IND_RENOVACION_AUTO>N</IND_RENOVACION_AUTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_EMPRESA>1</COD_EMPRESA>
    <COD_PRODUCTO>305</COD_PRODUCTO>
    <MONTO_MINIMO>50001</MONTO_MINIMO>
    <A_LA_VISTA>N</A_LA_VISTA>
    <FORMA_CALCULO_INTERES>CU</FORMA_CALCULO_INTERES>
    <FRE_CAPITALIZA>D</FRE_CAPITALIZA>
    <PAGA_RENTA>S</PAGA_RENTA>
    <PORCENTAJE_RENTA>1</PORCENTAJE_RENTA>
    <BASE_CALCULO>360</BASE_CALCULO>
    <BASE_PLAZO>365</BASE_PLAZO>
    <PLAZO_MINIMO>365</PLAZO_MINIMO>
    <ADICIONADO_POR>B2000</ADICIONADO_POR>
    <FECHA_ADICION>1999/11/22 00:00:00</FECHA_ADICION>
    <MODIFICADO_POR>MASANCHEZ</MODIFICADO_POR>
    <FECHA_MODIFICACION>2018/10/24 00:00:00</FECHA_MODIFICACION>
    <TIENE_DOC_FISICO>S</TIENE_DOC_FISICO>
    <MODIFICA_PLA_CAP>N</MODIFICA_PLA_CAP>
    <DIA_PAGO_INT>26</DIA_PAGO_INT>
    <COD_CARTERA>CDPLAPESOS</COD_CARTERA>
    <DIAS_EFECTIVO>0</DIAS_EFECTIVO>
    <DIAS_CHEQUE>0</DIAS_CHEQUE>
    <CODIGO_TIPO_INSTRUMENTO>221</CODIGO_TIPO_INSTRUMENTO>
    <IND_CALCULA_PENALIDAD>S</IND_CALCULA_PENALIDAD>
    <IND_PENALIDAD_RENOV>N</IND_PENALIDAD_RENOV>
    <IND_REDENCION_ANT>N</IND_REDENCION_ANT>
    <IND_BONOS>N</IND_BONOS>
    <IND_RENOVACION_AUTO>N</IND_RENOVACION_AUTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_EMPRESA>1</COD_EMPRESA>
    <COD_PRODUCTO>200</COD_PRODUCTO>
    <MONTO_MINIMO>1000</MONTO_MINIMO>
    <A_LA_VISTA>N</A_LA_VISTA>
    <FORMA_CALCULO_INTERES>CU</FORMA_CALCULO_INTERES>
    <FRE_CAPITALIZA>D</FRE_CAPITALIZA>
    <PAGA_RENTA>N</PAGA_RENTA>
    <BASE_CALCULO>360</BASE_CALCULO>
    <BASE_PLAZO>365</BASE_PLAZO>
    <PLAZO_MINIMO>30</PLAZO_MINIMO>
    <ADICIONADO_POR>B2000</ADICIONADO_POR>
    <FECHA_ADICION>2015/09/11 00:00:00</FECHA_ADICION>
    <TIENE_DOC_FISICO>S</TIENE_DOC_FISICO>
    <MODIFICA_PLA_CAP>S</MODIFICA_PLA_CAP>
    <DIA_PAGO_INT>31</DIA_PAGO_INT>
    <COD_CARTERA>CDPERDOLAR</COD_CARTERA>
    <DIAS_EFECTIVO>0</DIAS_EFECTIVO>
    <DIAS_CHEQUE>0</DIAS_CHEQUE>
    <MON_COM_EMISION_CHK>5</MON_COM_EMISION_CHK>
    <CODIGO_TIPO_INSTRUMENTO>221</CODIGO_TIPO_INSTRUMENTO>
    <IND_CALCULA_PENALIDAD>S</IND_CALCULA_PENALIDAD>
    <IND_PENALIDAD_RENOV>S</IND_PENALIDAD_RENOV>
    <IND_REDENCION_ANT>S</IND_REDENCION_ANT>
    <IND_BONOS>N</IND_BONOS>
    <IND_RENOVACION_AUTO>N</IND_RENOVACION_AUTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_EMPRESA>1</COD_EMPRESA>
    <COD_PRODUCTO>101</COD_PRODUCTO>
    <MONTO_MINIMO>1000</MONTO_MINIMO>
    <A_LA_VISTA>N</A_LA_VISTA>
    <FORMA_CALCULO_INTERES>CF</FORMA_CALCULO_INTERES>
    <FRE_CAPITALIZA>D</FRE_CAPITALIZA>
    <PLAZO_CAPITALIZA>30</PLAZO_CAPITALIZA>
    <PAGA_RENTA>N</PAGA_RENTA>
    <BASE_CALCULO>360</BASE_CALCULO>
    <BASE_PLAZO>365</BASE_PLAZO>
    <PLAZO_MINIMO>30</PLAZO_MINIMO>
    <ADICIONADO_POR>B2000</ADICIONADO_POR>
    <FECHA_ADICION>1999/11/22 00:00:00</FECHA_ADICION>
    <MODIFICADO_POR>B2000</MODIFICADO_POR>
    <FECHA_MODIFICACION>2011/07/11 00:00:00</FECHA_MODIFICACION>
    <TIENE_DOC_FISICO>S</TIENE_DOC_FISICO>
    <MODIFICA_PLA_CAP>N</MODIFICA_PLA_CAP>
    <DIA_PAGO_INT>31</DIA_PAGO_INT>
    <COD_CARTERA>CDPERPESOS</COD_CARTERA>
    <DIAS_EFECTIVO>0</DIAS_EFECTIVO>
    <DIAS_CHEQUE>0</DIAS_CHEQUE>
    <MON_COM_EMISION_CHK>0</MON_COM_EMISION_CHK>
    <CODIGO_TIPO_INSTRUMENTO>231</CODIGO_TIPO_INSTRUMENTO>
    <IND_CALCULA_PENALIDAD>S</IND_CALCULA_PENALIDAD>
    <IND_PENALIDAD_RENOV>S</IND_PENALIDAD_RENOV>
    <IND_REDENCION_ANT>S</IND_REDENCION_ANT>
    <IND_BONOS>N</IND_BONOS>
    <IND_RENOVACION_AUTO>N</IND_RENOVACION_AUTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_EMPRESA>1</COD_EMPRESA>
    <COD_PRODUCTO>100</COD_PRODUCTO>
    <MONTO_MINIMO>1000</MONTO_MINIMO>
    <A_LA_VISTA>N</A_LA_VISTA>
    <FORMA_CALCULO_INTERES>CF</FORMA_CALCULO_INTERES>
    <FRE_CAPITALIZA>D</FRE_CAPITALIZA>
    <PLAZO_CAPITALIZA>30</PLAZO_CAPITALIZA>
    <PAGA_RENTA>N</PAGA_RENTA>
    <BASE_CALCULO>360</BASE_CALCULO>
    <BASE_PLAZO>365</BASE_PLAZO>
    <PLAZO_MINIMO>30</PLAZO_MINIMO>
    <ADICIONADO_POR>B2000</ADICIONADO_POR>
    <FECHA_ADICION>1999/11/22 00:00:00</FECHA_ADICION>
    <MODIFICADO_POR>B2000</MODIFICADO_POR>
    <FECHA_MODIFICACION>2011/07/11 00:00:00</FECHA_MODIFICACION>
    <TIENE_DOC_FISICO>S</TIENE_DOC_FISICO>
    <MODIFICA_PLA_CAP>N</MODIFICA_PLA_CAP>
    <DIA_PAGO_INT>31</DIA_PAGO_INT>
    <COD_CARTERA>CDPERPESOS</COD_CARTERA>
    <DIAS_EFECTIVO>0</DIAS_EFECTIVO>
    <DIAS_CHEQUE>0</DIAS_CHEQUE>
    <MON_COM_EMISION_CHK>0</MON_COM_EMISION_CHK>
    <CODIGO_TIPO_INSTRUMENTO>231</CODIGO_TIPO_INSTRUMENTO>
    <IND_CALCULA_PENALIDAD>S</IND_CALCULA_PENALIDAD>
    <IND_PENALIDAD_RENOV>S</IND_PENALIDAD_RENOV>
    <IND_REDENCION_ANT>N</IND_REDENCION_ANT>
    <IND_BONOS>N</IND_BONOS>
    <IND_RENOVACION_AUTO>N</IND_RENOVACION_AUTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_EMPRESA>1</COD_EMPRESA>
    <COD_PRODUCTO>102</COD_PRODUCTO>
    <MONTO_MINIMO>1000</MONTO_MINIMO>
    <A_LA_VISTA>N</A_LA_VISTA>
    <FORMA_CALCULO_INTERES>CF</FORMA_CALCULO_INTERES>
    <FRE_CAPITALIZA>D</FRE_CAPITALIZA>
    <PLAZO_CAPITALIZA>30</PLAZO_CAPITALIZA>
    <PAGA_RENTA>N</PAGA_RENTA>
    <BASE_CALCULO>360</BASE_CALCULO>
    <BASE_PLAZO>365</BASE_PLAZO>
    <PLAZO_MINIMO>30</PLAZO_MINIMO>
    <ADICIONADO_POR>B2000</ADICIONADO_POR>
    <FECHA_ADICION>1999/11/22 00:00:00</FECHA_ADICION>
    <MODIFICADO_POR>B2000</MODIFICADO_POR>
    <FECHA_MODIFICACION>2011/07/11 00:00:00</FECHA_MODIFICACION>
    <TIENE_DOC_FISICO>S</TIENE_DOC_FISICO>
    <MODIFICA_PLA_CAP>N</MODIFICA_PLA_CAP>
    <DIA_PAGO_INT>31</DIA_PAGO_INT>
    <COD_CARTERA>CDPERPESOS</COD_CARTERA>
    <DIAS_EFECTIVO>0</DIAS_EFECTIVO>
    <DIAS_CHEQUE>0</DIAS_CHEQUE>
    <MON_COM_EMISION_CHK>0</MON_COM_EMISION_CHK>
    <CODIGO_TIPO_INSTRUMENTO>231</CODIGO_TIPO_INSTRUMENTO>
    <IND_CALCULA_PENALIDAD>S</IND_CALCULA_PENALIDAD>
    <IND_PENALIDAD_RENOV>S</IND_PENALIDAD_RENOV>
    <IND_REDENCION_ANT>S</IND_REDENCION_ANT>
    <IND_BONOS>N</IND_BONOS>
    <IND_RENOVACION_AUTO>N</IND_RENOVACION_AUTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_EMPRESA>1</COD_EMPRESA>
    <COD_PRODUCTO>103</COD_PRODUCTO>
    <MONTO_MINIMO>1000</MONTO_MINIMO>
    <A_LA_VISTA>N</A_LA_VISTA>
    <FORMA_CALCULO_INTERES>CF</FORMA_CALCULO_INTERES>
    <FRE_CAPITALIZA>D</FRE_CAPITALIZA>
    <PLAZO_CAPITALIZA>30</PLAZO_CAPITALIZA>
    <PAGA_RENTA>N</PAGA_RENTA>
    <BASE_CALCULO>360</BASE_CALCULO>
    <BASE_PLAZO>365</BASE_PLAZO>
    <PLAZO_MINIMO>30</PLAZO_MINIMO>
    <ADICIONADO_POR>B2000</ADICIONADO_POR>
    <FECHA_ADICION>1999/11/22 00:00:00</FECHA_ADICION>
    <MODIFICADO_POR>B2000</MODIFICADO_POR>
    <FECHA_MODIFICACION>2011/07/11 00:00:00</FECHA_MODIFICACION>
    <TIENE_DOC_FISICO>S</TIENE_DOC_FISICO>
    <MODIFICA_PLA_CAP>N</MODIFICA_PLA_CAP>
    <DIA_PAGO_INT>31</DIA_PAGO_INT>
    <COD_CARTERA>CDPERPESOS</COD_CARTERA>
    <DIAS_EFECTIVO>0</DIAS_EFECTIVO>
    <DIAS_CHEQUE>0</DIAS_CHEQUE>
    <MON_COM_EMISION_CHK>0</MON_COM_EMISION_CHK>
    <CODIGO_TIPO_INSTRUMENTO>231</CODIGO_TIPO_INSTRUMENTO>
    <IND_CALCULA_PENALIDAD>S</IND_CALCULA_PENALIDAD>
    <IND_PENALIDAD_RENOV>S</IND_PENALIDAD_RENOV>
    <IND_REDENCION_ANT>S</IND_REDENCION_ANT>
    <IND_BONOS>N</IND_BONOS>
    <IND_RENOVACION_AUTO>N</IND_RENOVACION_AUTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_EMPRESA>1</COD_EMPRESA>
    <COD_PRODUCTO>201</COD_PRODUCTO>
    <MONTO_MINIMO>1000</MONTO_MINIMO>
    <A_LA_VISTA>N</A_LA_VISTA>
    <FORMA_CALCULO_INTERES>CF</FORMA_CALCULO_INTERES>
    <FRE_CAPITALIZA>D</FRE_CAPITALIZA>
    <PLAZO_CAPITALIZA>30</PLAZO_CAPITALIZA>
    <PAGA_RENTA>N</PAGA_RENTA>
    <BASE_CALCULO>360</BASE_CALCULO>
    <BASE_PLAZO>365</BASE_PLAZO>
    <PLAZO_MINIMO>30</PLAZO_MINIMO>
    <ADICIONADO_POR>B2000</ADICIONADO_POR>
    <FECHA_ADICION>1999/11/22 00:00:00</FECHA_ADICION>
    <MODIFICADO_POR>B2000</MODIFICADO_POR>
    <FECHA_MODIFICACION>2011/07/11 00:00:00</FECHA_MODIFICACION>
    <TIENE_DOC_FISICO>S</TIENE_DOC_FISICO>
    <MODIFICA_PLA_CAP>N</MODIFICA_PLA_CAP>
    <DIA_PAGO_INT>31</DIA_PAGO_INT>
    <COD_CARTERA>CDPERPESOS</COD_CARTERA>
    <DIAS_EFECTIVO>0</DIAS_EFECTIVO>
    <DIAS_CHEQUE>0</DIAS_CHEQUE>
    <MON_COM_EMISION_CHK>0</MON_COM_EMISION_CHK>
    <CODIGO_TIPO_INSTRUMENTO>231</CODIGO_TIPO_INSTRUMENTO>
    <IND_CALCULA_PENALIDAD>S</IND_CALCULA_PENALIDAD>
    <IND_PENALIDAD_RENOV>S</IND_PENALIDAD_RENOV>
    <IND_REDENCION_ANT>S</IND_REDENCION_ANT>
    <IND_BONOS>N</IND_BONOS>
    <IND_RENOVACION_AUTO>N</IND_RENOVACION_AUTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_EMPRESA>1</COD_EMPRESA>
    <COD_PRODUCTO>202</COD_PRODUCTO>
    <MONTO_MINIMO>1000</MONTO_MINIMO>
    <A_LA_VISTA>N</A_LA_VISTA>
    <FORMA_CALCULO_INTERES>CF</FORMA_CALCULO_INTERES>
    <FRE_CAPITALIZA>D</FRE_CAPITALIZA>
    <PLAZO_CAPITALIZA>30</PLAZO_CAPITALIZA>
    <PAGA_RENTA>N</PAGA_RENTA>
    <BASE_CALCULO>360</BASE_CALCULO>
    <BASE_PLAZO>365</BASE_PLAZO>
    <PLAZO_MINIMO>30</PLAZO_MINIMO>
    <ADICIONADO_POR>B2000</ADICIONADO_POR>
    <FECHA_ADICION>1999/11/22 00:00:00</FECHA_ADICION>
    <MODIFICADO_POR>B2000</MODIFICADO_POR>
    <FECHA_MODIFICACION>2011/07/11 00:00:00</FECHA_MODIFICACION>
    <TIENE_DOC_FISICO>S</TIENE_DOC_FISICO>
    <MODIFICA_PLA_CAP>N</MODIFICA_PLA_CAP>
    <DIA_PAGO_INT>31</DIA_PAGO_INT>
    <COD_CARTERA>CDPERPESOS</COD_CARTERA>
    <DIAS_EFECTIVO>0</DIAS_EFECTIVO>
    <DIAS_CHEQUE>0</DIAS_CHEQUE>
    <MON_COM_EMISION_CHK>0</MON_COM_EMISION_CHK>
    <CODIGO_TIPO_INSTRUMENTO>231</CODIGO_TIPO_INSTRUMENTO>
    <IND_CALCULA_PENALIDAD>S</IND_CALCULA_PENALIDAD>
    <IND_PENALIDAD_RENOV>S</IND_PENALIDAD_RENOV>
    <IND_REDENCION_ANT>S</IND_REDENCION_ANT>
    <IND_BONOS>N</IND_BONOS>
    <IND_RENOVACION_AUTO>N</IND_RENOVACION_AUTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_EMPRESA>1</COD_EMPRESA>
    <COD_PRODUCTO>203</COD_PRODUCTO>
    <MONTO_MINIMO>1000</MONTO_MINIMO>
    <A_LA_VISTA>N</A_LA_VISTA>
    <FORMA_CALCULO_INTERES>CF</FORMA_CALCULO_INTERES>
    <FRE_CAPITALIZA>D</FRE_CAPITALIZA>
    <PLAZO_CAPITALIZA>30</PLAZO_CAPITALIZA>
    <PAGA_RENTA>N</PAGA_RENTA>
    <BASE_CALCULO>360</BASE_CALCULO>
    <BASE_PLAZO>365</BASE_PLAZO>
    <PLAZO_MINIMO>30</PLAZO_MINIMO>
    <ADICIONADO_POR>B2000</ADICIONADO_POR>
    <FECHA_ADICION>1999/11/22 00:00:00</FECHA_ADICION>
    <MODIFICADO_POR>B2000</MODIFICADO_POR>
    <FECHA_MODIFICACION>2011/07/11 00:00:00</FECHA_MODIFICACION>
    <TIENE_DOC_FISICO>S</TIENE_DOC_FISICO>
    <MODIFICA_PLA_CAP>N</MODIFICA_PLA_CAP>
    <DIA_PAGO_INT>31</DIA_PAGO_INT>
    <COD_CARTERA>CDPERPESOS</COD_CARTERA>
    <DIAS_EFECTIVO>0</DIAS_EFECTIVO>
    <DIAS_CHEQUE>0</DIAS_CHEQUE>
    <MON_COM_EMISION_CHK>0</MON_COM_EMISION_CHK>
    <CODIGO_TIPO_INSTRUMENTO>231</CODIGO_TIPO_INSTRUMENTO>
    <IND_CALCULA_PENALIDAD>S</IND_CALCULA_PENALIDAD>
    <IND_PENALIDAD_RENOV>S</IND_PENALIDAD_RENOV>
    <IND_REDENCION_ANT>S</IND_REDENCION_ANT>
    <IND_BONOS>N</IND_BONOS>
    <IND_RENOVACION_AUTO>N</IND_RENOVACION_AUTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_EMPRESA>1</COD_EMPRESA>
    <COD_PRODUCTO>204</COD_PRODUCTO>
    <MONTO_MINIMO>1000</MONTO_MINIMO>
    <A_LA_VISTA>N</A_LA_VISTA>
    <FORMA_CALCULO_INTERES>CU</FORMA_CALCULO_INTERES>
    <FRE_CAPITALIZA>D</FRE_CAPITALIZA>
    <PAGA_RENTA>N</PAGA_RENTA>
    <BASE_CALCULO>360</BASE_CALCULO>
    <BASE_PLAZO>365</BASE_PLAZO>
    <PLAZO_MINIMO>30</PLAZO_MINIMO>
    <ADICIONADO_POR>B2000</ADICIONADO_POR>
    <FECHA_ADICION>1999/11/22 00:00:00</FECHA_ADICION>
    <MODIFICADO_POR>B2000</MODIFICADO_POR>
    <FECHA_MODIFICACION>2014/03/04 00:00:00</FECHA_MODIFICACION>
    <TIENE_DOC_FISICO>S</TIENE_DOC_FISICO>
    <MODIFICA_PLA_CAP>S</MODIFICA_PLA_CAP>
    <DIA_PAGO_INT>31</DIA_PAGO_INT>
    <COD_CARTERA>CDPERPESOS</COD_CARTERA>
    <DIAS_EFECTIVO>0</DIAS_EFECTIVO>
    <DIAS_CHEQUE>0</DIAS_CHEQUE>
    <MON_COM_EMISION_CHK>200</MON_COM_EMISION_CHK>
    <CODIGO_TIPO_INSTRUMENTO>231</CODIGO_TIPO_INSTRUMENTO>
    <IND_CALCULA_PENALIDAD>S</IND_CALCULA_PENALIDAD>
    <IND_PENALIDAD_RENOV>S</IND_PENALIDAD_RENOV>
    <IND_REDENCION_ANT>S</IND_REDENCION_ANT>
    <IND_BONOS>N</IND_BONOS>
    <IND_RENOVACION_AUTO>N</IND_RENOVACION_AUTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_EMPRESA>1</COD_EMPRESA>
    <COD_PRODUCTO>205</COD_PRODUCTO>
    <MONTO_MINIMO>1000</MONTO_MINIMO>
    <A_LA_VISTA>N</A_LA_VISTA>
    <FORMA_CALCULO_INTERES>CF</FORMA_CALCULO_INTERES>
    <FRE_CAPITALIZA>D</FRE_CAPITALIZA>
    <PLAZO_CAPITALIZA>30</PLAZO_CAPITALIZA>
    <PAGA_RENTA>N</PAGA_RENTA>
    <BASE_CALCULO>360</BASE_CALCULO>
    <BASE_PLAZO>365</BASE_PLAZO>
    <PLAZO_MINIMO>30</PLAZO_MINIMO>
    <ADICIONADO_POR>B2000</ADICIONADO_POR>
    <FECHA_ADICION>1999/11/22 00:00:00</FECHA_ADICION>
    <MODIFICADO_POR>B2000</MODIFICADO_POR>
    <FECHA_MODIFICACION>2011/07/11 00:00:00</FECHA_MODIFICACION>
    <TIENE_DOC_FISICO>S</TIENE_DOC_FISICO>
    <MODIFICA_PLA_CAP>N</MODIFICA_PLA_CAP>
    <DIA_PAGO_INT>31</DIA_PAGO_INT>
    <COD_CARTERA>CDPERPESOS</COD_CARTERA>
    <DIAS_EFECTIVO>0</DIAS_EFECTIVO>
    <DIAS_CHEQUE>0</DIAS_CHEQUE>
    <MON_COM_EMISION_CHK>0</MON_COM_EMISION_CHK>
    <CODIGO_TIPO_INSTRUMENTO>231</CODIGO_TIPO_INSTRUMENTO>
    <IND_CALCULA_PENALIDAD>S</IND_CALCULA_PENALIDAD>
    <IND_PENALIDAD_RENOV>S</IND_PENALIDAD_RENOV>
    <IND_REDENCION_ANT>S</IND_REDENCION_ANT>
    <IND_BONOS>N</IND_BONOS>
    <IND_RENOVACION_AUTO>N</IND_RENOVACION_AUTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_EMPRESA>1</COD_EMPRESA>
    <COD_PRODUCTO>500</COD_PRODUCTO>
    <MONTO_MINIMO>1000</MONTO_MINIMO>
    <A_LA_VISTA>N</A_LA_VISTA>
    <FORMA_CALCULO_INTERES>CF</FORMA_CALCULO_INTERES>
    <FRE_CAPITALIZA>D</FRE_CAPITALIZA>
    <PLAZO_CAPITALIZA>30</PLAZO_CAPITALIZA>
    <PAGA_RENTA>N</PAGA_RENTA>
    <BASE_CALCULO>360</BASE_CALCULO>
    <BASE_PLAZO>365</BASE_PLAZO>
    <PLAZO_MINIMO>30</PLAZO_MINIMO>
    <ADICIONADO_POR>B2000</ADICIONADO_POR>
    <FECHA_ADICION>1999/11/22 00:00:00</FECHA_ADICION>
    <MODIFICADO_POR>B2000</MODIFICADO_POR>
    <FECHA_MODIFICACION>2011/07/11 00:00:00</FECHA_MODIFICACION>
    <TIENE_DOC_FISICO>S</TIENE_DOC_FISICO>
    <MODIFICA_PLA_CAP>N</MODIFICA_PLA_CAP>
    <DIA_PAGO_INT>31</DIA_PAGO_INT>
    <COD_CARTERA>CDPERPESOS</COD_CARTERA>
    <DIAS_EFECTIVO>0</DIAS_EFECTIVO>
    <DIAS_CHEQUE>0</DIAS_CHEQUE>
    <MON_COM_EMISION_CHK>0</MON_COM_EMISION_CHK>
    <CODIGO_TIPO_INSTRUMENTO>231</CODIGO_TIPO_INSTRUMENTO>
    <IND_CALCULA_PENALIDAD>S</IND_CALCULA_PENALIDAD>
    <IND_PENALIDAD_RENOV>S</IND_PENALIDAD_RENOV>
    <IND_REDENCION_ANT>S</IND_REDENCION_ANT>
    <IND_BONOS>N</IND_BONOS>
    <IND_RENOVACION_AUTO>N</IND_RENOVACION_AUTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_EMPRESA>1</COD_EMPRESA>
    <COD_PRODUCTO>501</COD_PRODUCTO>
    <MONTO_MINIMO>1000</MONTO_MINIMO>
    <A_LA_VISTA>N</A_LA_VISTA>
    <FORMA_CALCULO_INTERES>CF</FORMA_CALCULO_INTERES>
    <FRE_CAPITALIZA>D</FRE_CAPITALIZA>
    <PLAZO_CAPITALIZA>30</PLAZO_CAPITALIZA>
    <PAGA_RENTA>N</PAGA_RENTA>
    <BASE_CALCULO>360</BASE_CALCULO>
    <BASE_PLAZO>365</BASE_PLAZO>
    <PLAZO_MINIMO>30</PLAZO_MINIMO>
    <ADICIONADO_POR>B2000</ADICIONADO_POR>
    <FECHA_ADICION>1999/11/22 00:00:00</FECHA_ADICION>
    <MODIFICADO_POR>B2000</MODIFICADO_POR>
    <FECHA_MODIFICACION>2011/07/11 00:00:00</FECHA_MODIFICACION>
    <TIENE_DOC_FISICO>S</TIENE_DOC_FISICO>
    <MODIFICA_PLA_CAP>N</MODIFICA_PLA_CAP>
    <DIA_PAGO_INT>31</DIA_PAGO_INT>
    <COD_CARTERA>CDPERPESOS</COD_CARTERA>
    <DIAS_EFECTIVO>0</DIAS_EFECTIVO>
    <DIAS_CHEQUE>0</DIAS_CHEQUE>
    <MON_COM_EMISION_CHK>0</MON_COM_EMISION_CHK>
    <CODIGO_TIPO_INSTRUMENTO>231</CODIGO_TIPO_INSTRUMENTO>
    <IND_CALCULA_PENALIDAD>S</IND_CALCULA_PENALIDAD>
    <IND_PENALIDAD_RENOV>S</IND_PENALIDAD_RENOV>
    <IND_REDENCION_ANT>S</IND_REDENCION_ANT>
    <IND_BONOS>N</IND_BONOS>
    <IND_RENOVACION_AUTO>N</IND_RENOVACION_AUTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_EMPRESA>1</COD_EMPRESA>
    <COD_PRODUCTO>502</COD_PRODUCTO>
    <MONTO_MINIMO>1000</MONTO_MINIMO>
    <A_LA_VISTA>N</A_LA_VISTA>
    <FORMA_CALCULO_INTERES>CF</FORMA_CALCULO_INTERES>
    <FRE_CAPITALIZA>D</FRE_CAPITALIZA>
    <PLAZO_CAPITALIZA>30</PLAZO_CAPITALIZA>
    <PAGA_RENTA>N</PAGA_RENTA>
    <BASE_CALCULO>360</BASE_CALCULO>
    <BASE_PLAZO>365</BASE_PLAZO>
    <PLAZO_MINIMO>30</PLAZO_MINIMO>
    <ADICIONADO_POR>B2000</ADICIONADO_POR>
    <FECHA_ADICION>1999/11/22 00:00:00</FECHA_ADICION>
    <MODIFICADO_POR>B2000</MODIFICADO_POR>
    <FECHA_MODIFICACION>2011/07/11 00:00:00</FECHA_MODIFICACION>
    <TIENE_DOC_FISICO>S</TIENE_DOC_FISICO>
    <MODIFICA_PLA_CAP>N</MODIFICA_PLA_CAP>
    <DIA_PAGO_INT>31</DIA_PAGO_INT>
    <COD_CARTERA>CDPERPESOS</COD_CARTERA>
    <DIAS_EFECTIVO>0</DIAS_EFECTIVO>
    <DIAS_CHEQUE>0</DIAS_CHEQUE>
    <MON_COM_EMISION_CHK>0</MON_COM_EMISION_CHK>
    <CODIGO_TIPO_INSTRUMENTO>231</CODIGO_TIPO_INSTRUMENTO>
    <IND_CALCULA_PENALIDAD>S</IND_CALCULA_PENALIDAD>
    <IND_PENALIDAD_RENOV>S</IND_PENALIDAD_RENOV>
    <IND_REDENCION_ANT>S</IND_REDENCION_ANT>
    <IND_BONOS>N</IND_BONOS>
    <IND_RENOVACION_AUTO>N</IND_RENOVACION_AUTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_EMPRESA>1</COD_EMPRESA>
    <COD_PRODUCTO>320</COD_PRODUCTO>
    <MONTO_MINIMO>500</MONTO_MINIMO>
    <A_LA_VISTA>N</A_LA_VISTA>
    <FORMA_CALCULO_INTERES>CU</FORMA_CALCULO_INTERES>
    <FRE_CAPITALIZA>D</FRE_CAPITALIZA>
    <PLAZO_CAPITALIZA>30</PLAZO_CAPITALIZA>
    <PAGA_RENTA>S</PAGA_RENTA>
    <PORCENTAJE_RENTA>10</PORCENTAJE_RENTA>
    <BASE_CALCULO>360</BASE_CALCULO>
    <BASE_PLAZO>365</BASE_PLAZO>
    <PLAZO_MINIMO>30</PLAZO_MINIMO>
    <ADICIONADO_POR>B2000</ADICIONADO_POR>
    <FECHA_ADICION>2015/12/21 00:00:00</FECHA_ADICION>
    <MODIFICADO_POR>ICUEVA</MODIFICADO_POR>
    <FECHA_MODIFICACION>2022/07/08 00:00:00</FECHA_MODIFICACION>
    <TIENE_DOC_FISICO>S</TIENE_DOC_FISICO>
    <MODIFICA_PLA_CAP>N</MODIFICA_PLA_CAP>
    <DIA_PAGO_INT>26</DIA_PAGO_INT>
    <COD_CARTERA>CDPERDOLAR</COD_CARTERA>
    <DIAS_EFECTIVO>0</DIAS_EFECTIVO>
    <DIAS_CHEQUE>0</DIAS_CHEQUE>
    <CODIGO_TIPO_INSTRUMENTO>231</CODIGO_TIPO_INSTRUMENTO>
    <IND_CALCULA_PENALIDAD>S</IND_CALCULA_PENALIDAD>
    <IND_PENALIDAD_RENOV>N</IND_PENALIDAD_RENOV>
    <IND_REDENCION_ANT>S</IND_REDENCION_ANT>
    <IND_BONOS>N</IND_BONOS>
    <IND_RENOVACION_AUTO>S</IND_RENOVACION_AUTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_EMPRESA>1</COD_EMPRESA>
    <COD_PRODUCTO>321</COD_PRODUCTO>
    <MONTO_MINIMO>500</MONTO_MINIMO>
    <A_LA_VISTA>N</A_LA_VISTA>
    <FORMA_CALCULO_INTERES>CU</FORMA_CALCULO_INTERES>
    <FRE_CAPITALIZA>D</FRE_CAPITALIZA>
    <PLAZO_CAPITALIZA>30</PLAZO_CAPITALIZA>
    <PAGA_RENTA>S</PAGA_RENTA>
    <PORCENTAJE_RENTA>1</PORCENTAJE_RENTA>
    <BASE_CALCULO>360</BASE_CALCULO>
    <BASE_PLAZO>365</BASE_PLAZO>
    <PLAZO_MINIMO>30</PLAZO_MINIMO>
    <ADICIONADO_POR>B2000</ADICIONADO_POR>
    <FECHA_ADICION>2015/12/21 00:00:00</FECHA_ADICION>
    <MODIFICADO_POR>ICUEVA</MODIFICADO_POR>
    <FECHA_MODIFICACION>2022/07/08 00:00:00</FECHA_MODIFICACION>
    <TIENE_DOC_FISICO>S</TIENE_DOC_FISICO>
    <MODIFICA_PLA_CAP>N</MODIFICA_PLA_CAP>
    <DIA_PAGO_INT>26</DIA_PAGO_INT>
    <COD_CARTERA>CDCOMDOLAR</COD_CARTERA>
    <DIAS_EFECTIVO>0</DIAS_EFECTIVO>
    <DIAS_CHEQUE>0</DIAS_CHEQUE>
    <CODIGO_TIPO_INSTRUMENTO>231</CODIGO_TIPO_INSTRUMENTO>
    <IND_CALCULA_PENALIDAD>S</IND_CALCULA_PENALIDAD>
    <IND_PENALIDAD_RENOV>N</IND_PENALIDAD_RENOV>
    <IND_REDENCION_ANT>S</IND_REDENCION_ANT>
    <IND_BONOS>N</IND_BONOS>
    <IND_RENOVACION_AUTO>S</IND_RENOVACION_AUTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_EMPRESA>1</COD_EMPRESA>
    <COD_PRODUCTO>322</COD_PRODUCTO>
    <MONTO_MINIMO>500</MONTO_MINIMO>
    <A_LA_VISTA>N</A_LA_VISTA>
    <FORMA_CALCULO_INTERES>CV</FORMA_CALCULO_INTERES>
    <FRE_CAPITALIZA>D</FRE_CAPITALIZA>
    <PLAZO_CAPITALIZA>30</PLAZO_CAPITALIZA>
    <PAGA_RENTA>S</PAGA_RENTA>
    <PORCENTAJE_RENTA>10</PORCENTAJE_RENTA>
    <BASE_CALCULO>360</BASE_CALCULO>
    <BASE_PLAZO>365</BASE_PLAZO>
    <PLAZO_MINIMO>30</PLAZO_MINIMO>
    <ADICIONADO_POR>B2000</ADICIONADO_POR>
    <FECHA_ADICION>2015/12/21 00:00:00</FECHA_ADICION>
    <MODIFICADO_POR>ICUEVA</MODIFICADO_POR>
    <FECHA_MODIFICACION>2022/07/08 00:00:00</FECHA_MODIFICACION>
    <TIENE_DOC_FISICO>S</TIENE_DOC_FISICO>
    <MODIFICA_PLA_CAP>N</MODIFICA_PLA_CAP>
    <DIA_PAGO_INT>26</DIA_PAGO_INT>
    <COD_CARTERA>CDPERDOLAR</COD_CARTERA>
    <DIAS_EFECTIVO>0</DIAS_EFECTIVO>
    <DIAS_CHEQUE>0</DIAS_CHEQUE>
    <CODIGO_TIPO_INSTRUMENTO>231</CODIGO_TIPO_INSTRUMENTO>
    <IND_CALCULA_PENALIDAD>S</IND_CALCULA_PENALIDAD>
    <IND_PENALIDAD_RENOV>N</IND_PENALIDAD_RENOV>
    <IND_REDENCION_ANT>S</IND_REDENCION_ANT>
    <IND_BONOS>N</IND_BONOS>
    <IND_RENOVACION_AUTO>S</IND_RENOVACION_AUTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_EMPRESA>1</COD_EMPRESA>
    <COD_PRODUCTO>323</COD_PRODUCTO>
    <MONTO_MINIMO>500</MONTO_MINIMO>
    <A_LA_VISTA>N</A_LA_VISTA>
    <FORMA_CALCULO_INTERES>CV</FORMA_CALCULO_INTERES>
    <FRE_CAPITALIZA>D</FRE_CAPITALIZA>
    <PLAZO_CAPITALIZA>30</PLAZO_CAPITALIZA>
    <PAGA_RENTA>S</PAGA_RENTA>
    <PORCENTAJE_RENTA>1</PORCENTAJE_RENTA>
    <BASE_CALCULO>360</BASE_CALCULO>
    <BASE_PLAZO>365</BASE_PLAZO>
    <PLAZO_MINIMO>30</PLAZO_MINIMO>
    <ADICIONADO_POR>B2000</ADICIONADO_POR>
    <FECHA_ADICION>2015/12/21 00:00:00</FECHA_ADICION>
    <MODIFICADO_POR>ICUEVA</MODIFICADO_POR>
    <FECHA_MODIFICACION>2022/07/08 00:00:00</FECHA_MODIFICACION>
    <TIENE_DOC_FISICO>S</TIENE_DOC_FISICO>
    <MODIFICA_PLA_CAP>N</MODIFICA_PLA_CAP>
    <DIA_PAGO_INT>26</DIA_PAGO_INT>
    <COD_CARTERA>CDCOMDOLAR</COD_CARTERA>
    <DIAS_EFECTIVO>0</DIAS_EFECTIVO>
    <DIAS_CHEQUE>0</DIAS_CHEQUE>
    <CODIGO_TIPO_INSTRUMENTO>231</CODIGO_TIPO_INSTRUMENTO>
    <IND_CALCULA_PENALIDAD>S</IND_CALCULA_PENALIDAD>
    <IND_PENALIDAD_RENOV>N</IND_PENALIDAD_RENOV>
    <IND_REDENCION_ANT>S</IND_REDENCION_ANT>
    <IND_BONOS>N</IND_BONOS>
    <IND_RENOVACION_AUTO>S</IND_RENOVACION_AUTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <COD_EMPRESA>1</COD_EMPRESA>